"""Subclass of MyFrame1, which is generated by wxFormBuilder."""

import wx
import test1
import MyClassMyFrame2


# from MyClassMyFrame2 import MyClassMyFrame4
# Implementing MyFrame1

class MyClassMyFrame1(test1.MyFrame1):
    def __init__(self, parent):
        test1.MyFrame1.__init__(self, parent)

        # イベント処理時、どのメソッドを呼び出すかを登録する
        self.m_button1.Bind(wx.EVT_BUTTON, self.OnButtonPress1)

    # イベント処理を記載
    def OnButtonPress1(self, event):
        a = MyClassMyFrame2.zzz()
        self.m_textCtrl1.SetLabel(a)

        # イベント処理時、どのメソッドを呼び出すかを登録する
        self.m_button2.Bind(wx.EVT_BUTTON, self.OnButtonPress2)

    # イベント処理を記載
    def OnButtonPress2(self, event):
        self.m_textCtrl2.SetLabel('24124124123412341241')
